version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - govet
  disable:
    - depguard  # Disable depguard since we need terraform and crypto imports
    - gocyclo   # Disable complexity checks for now
    - gocritic  # Disable gocritic for now