run:
  timeout: 5m
  go: '1.23'

linters-settings:
  gocyclo:
    min-complexity: 20  # Allow higher complexity for tests
  depguard:
    rules:
      main:
        deny:
          # Remove restrictions on terraform-plugin-log and crypto packages
          # These are legitimate dependencies for a Terraform provider
  gocritic:
    disabled-checks:
      - hugeParam  # Allow large parameter structs in provider code

linters:
  enable:
    - errcheck
    - gocyclo
    - gocritic
    - staticcheck
    - unused
    - gosimple
    - govet
  disable:
    - depguard  # Disable depguard since we need terraform and crypto imports

issues:
  exclude-rules:
    # Allow time.Sleep in tests for timeout testing
    - path: _test\.go
      text: "time.Sleep"
    # Allow errcheck skip for test response writers
    - path: _test\.go
      linters:
        - errcheck
    # Allow higher complexity in test functions
    - path: _test\.go
      linters:
        - gocyclo